import EoneUtility from '../utility/EoneUtility';
import { basename } from 'path';
var scriptName = basename(__filename).replace(".js","");
	
import { configure } from '../utility/LogUtilty';
var startFlag;
configure(scriptName);

describe('FT_MFG_R40G031_GrowingAreacodeWithHierarchyAndAppellationcodePOonly', function() {

    it('Step 1 : Start Script:03 R40G031 Test Growing Area code with Hierarchy and Appellation code Proc Opt only', function () {
    startFlag = EoneUtility.startFlag();
    EoneUtility.startE1();     
    EoneUtility.UBESubmit('R40G031_QA40G031B');
    EoneUtility.UBEGetXML('R40G031_QA40G031B');
    var result = EoneUtility.XML2JSON('R40G031_QA40G031B');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[8].$.Value','Yes');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[9].$.Value','GNC');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[10].$.Value','Growing Area');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[11].$.Value','Block');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[12].$.Value','Code');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[13].$.Value','Harvest');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[14].$.Value','Period');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[15].$.Value','Harvest');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[16].$.Value','Suffix');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[17].$.Value','Block');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[18].$.Value','Name');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[19].$.Value','Variety');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[20].$.Value','Code');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[21].$.Value','District');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[22].$.Value','Appellation');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[23].$.Value','Region');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[24].$.Value','Growing');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[25].$.Value','Area');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[26].$.Value','Current');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[27].$.Value','Estimate');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[28].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[29].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[30].$.Value','Received');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[31].$.Value','Quantity');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[32].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[33].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[34].$.Value','Maximum');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[35].$.Value','Quantity');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[36].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[37].$.Value','Harvest');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[38].$.Value','Status');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[39].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[40].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[41].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[42].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[43].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[44].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[45].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[46].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[47].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[48].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[49].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[50].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[51].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[52].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[53].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[54].$.Value','');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[55].$.Value','Contract Code');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[56].$.Value','HVL');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[57].$.Value','Grower Representative');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[58].$.Value','Contract Representative');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[59].$.Value','Donna Driscoll');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[60].$.Value','Contract Name');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[61].$.Value','Harvest Listing Report');
    EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[62].$.Value','Mike Snow');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[63].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[64].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[65].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[66].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[67].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[68].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[69].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[70].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[71].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[72].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[73].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[74].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[75].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[76].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[77].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[78].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[79].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[80].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[81].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[82].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[83].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[84].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[85].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[86].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[87].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[88].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[89].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[90].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[90].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[91].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[92].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[93].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[94].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[95].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[96].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[97].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[98].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[99].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[100].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[101].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[102].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[103].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[104].$.Value','');
    // EoneUtility.nodeValueTest(result,'BatchOutput.Pages.Page.Item[105].$.Value','');
    EoneUtility.evaluateTime(startFlag);
    });
});    